-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 15:30:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PHPDieppe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PHPDieppe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PHPDieppe` DEFAULT CHARACTER SET utf8 ;
USE `PHPDieppe` ;

-- -----------------------------------------------------
-- Table `PHPDieppe`.`T_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHPDieppe`.`T_Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `rol_label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PHPDieppe`.`T_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHPDieppe`.`T_Users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `use_name` VARCHAR(45) NOT NULL,
  `use_firstname` VARCHAR(45) NULL,
  `use_mail` VARCHAR(160) NOT NULL,
  `use_password` CHAR(40) NULL,
  `T_Userscol` VARCHAR(45) NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idRole`),
  INDEX `fk_T_Users_T_Roles_idx` (`idRole` ASC),
  CONSTRAINT `fk_T_Users_T_Roles`
    FOREIGN KEY (`idRole`)
    REFERENCES `PHPDieppe`.`T_Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PHPDieppe`.`T_Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHPDieppe`.`T_Articles` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `art_title` VARCHAR(200) NOT NULL,
  `art_chapo` VARCHAR(200) NULL,
  `art_content` TEXT NOT NULL,
  `art_datetime` DATETIME NULL,
  `idUser` INT NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idArticle`, `idUser`, `idRole`),
  INDEX `fk_T_Articles_T_Users1_idx` (`idUser` ASC, `idRole` ASC),
  CONSTRAINT `fk_T_Articles_T_Users1`
    FOREIGN KEY (`idUser` , `idRole`)
    REFERENCES `PHPDieppe`.`T_Users` (`idUser` , `idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PHPDieppe`.`T_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHPDieppe`.`T_Categories` (
  `idCategories` INT NOT NULL AUTO_INCREMENT,
  `cat_label` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PHPDieppe`.`T_Articles_has_T_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHPDieppe`.`T_Articles_has_T_Categories` (
  `T_Articles_idArticle` INT NOT NULL,
  `T_Articles_idUser` INT NOT NULL,
  `T_Articles_idRole` INT NOT NULL,
  `T_Categories_idCategories` INT NOT NULL,
  PRIMARY KEY (`T_Articles_idArticle`, `T_Articles_idUser`, `T_Articles_idRole`, `T_Categories_idCategories`),
  INDEX `fk_T_Articles_has_T_Categories_T_Categories1_idx` (`T_Categories_idCategories` ASC),
  INDEX `fk_T_Articles_has_T_Categories_T_Articles1_idx` (`T_Articles_idArticle` ASC, `T_Articles_idUser` ASC, `T_Articles_idRole` ASC),
  CONSTRAINT `fk_T_Articles_has_T_Categories_T_Articles1`
    FOREIGN KEY (`T_Articles_idArticle` , `T_Articles_idUser` , `T_Articles_idRole`)
    REFERENCES `PHPDieppe`.`T_Articles` (`idArticle` , `idUser` , `idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Articles_has_T_Categories_T_Categories1`
    FOREIGN KEY (`T_Categories_idCategories`)
    REFERENCES `PHPDieppe`.`T_Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
